# Generated by Django 6.0.4 on 2026-04-27 20:56

import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#4CAF50', max_length=7, validators=[habits.validators.validate_color]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, validators=[habits.validators.validate_forbidden_words]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_count',
            field=models.PositiveIntegerField(default=1, validators=[habits.validators.validate_target_count]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=100, validators=[habits.validators.validate_habit_title, habits.validators.validate_forbidden_words]),
        ),
    ]
