# Generated by Django 6.0.4 on 2026-04-27 22:13

import django.db.models.deletion
import django.utils.timezone
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_color_alter_habit_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterModelOptions(
            name='habitcompletion',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Выполнение привычки', 'verbose_name_plural': 'Выполнения привычек'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#4CAF50', max_length=7, validators=[habits.validators.validate_color], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, validators=[habits.validators.validate_forbidden_words], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=20, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_count',
            field=models.PositiveIntegerField(default=1, validators=[habits.validators.validate_target_count], verbose_name='Целевое количество'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=100, validators=[habits.validators.validate_habit_title, habits.validators.validate_forbidden_words], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='completed_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit', verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заметка'),
        ),
    ]
